version: '3'

services:
  stateless-auth-db:
    container_name: stateless-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - auth
  stateful-auth-db:
    container_name: stateful-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - auth
  token-redis:
    container_name: token-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - auth
networks:
  auth:
    driver: bridge